name: Actions Workflow

on: [push]
jobs:
  jb-run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple python script Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: jb-run-github-actions
      - name: Log Greeting time
        run: echo "${{steps.greet.outputs.time }}"