name: Shell Commands-1

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: >
          node -v
          npm -v
        shell: bash

      - name: Display the path
        run: echo $PATH
        shell: bash

      - name: python Command
        run: |
          import platform
          print (platform.processor())
        shell: python

      - name: add numbers
        run: |
          a = 10
          b = 20
          c = a + b
          echo "sum of a + b is " c
        shell: bash

  User-Executing-Script:
      runs-on: ubuntu-latest
      steps:
        - name: username
          run: echo "User executing this script is Sardar"
