name: Shell Commands-1

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: >
          node -v
          npm -v
  User-Executing-Script:
      runs-on: ubuntu-latest
      steps:
        - name: username
          run: echo "User executing this script is Sardar"
