on: 
  push:
    branches:
      - context

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Set env variable
        env: 
          emp_name: "Javed"
          run: |
            echo "emp_name: ${emp_name}"       

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump Env context
        run: echo "${{ toJSON(env) }}"