name: wf_first

on: push

jobs:
  job1:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Print Todays Date
      run: date

  job2:
    name: Windows
    runs-on: windows-latest 
    steps:
    - name: Print Todays Date
      run: Get-Date

  job3:
    name: MacOS
    runs-on: macos-latest 
    steps:
    - name: Print Todays Date
      run: date


  job4:
    name: Depends
    needs: [Ubuntu, Windows, MacOS]
    runs-on: windows-latest 
    steps:
    - name: Print Todays Date
      run: Get-Date

