name: wf_first

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Print Todays Date in ubuntu
      run: date

  windows:
    runs-on: windows-latest 
    steps:
    - name: Print Todays Date in windows
      run: Get-Date

  macos:
    runs-on: macos-latest 
    steps:
    - name: Print Todays Date in macos
      run: date

  depends:
    needs: [ubuntu, windows, macos]
    runs-on: windows-latest 
    steps:
    - name: Print Todays Date in windows
      run: Get-Date

