name: wf_first

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    name: Job1 - Print date in ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Print Todays Date
      run: date

  job2:
    name: Job2 - Print date in windows
    runs-on: windows-latest 
    steps:
    - name: Print Todays Date
      run: Get-Date
