name: wf_first

on: push

jobs:
  job1:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Print Todays Date
      run: date

  job2:
    name: windows
    runs-on: windows-latest 
    steps:
    - name: Print Todays Date
      run: Get-Date

  job3:
    name: mac
    runs-on: macos-latest 
    steps:
    - name: Print Todays Date
      run: date


  job4:
    name: depends
    needs: [ubuntu,windows,mac]
    runs-on: windows-latest 
    steps:
    - name: Print Todays Date
      run: Get-Date

