name: Strategy and Matrix

on:
  push:
    branches:
      - matrix

jobs:
  python_version: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.8]
    
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python
    uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"