name: Build Tomcat

on: 
  push:
    branches:
      - passing-arguments-to-actions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out tomcat-users.xml
      uses: actions/checkout@v2

    - name: List project files and java version
      run: |
          ls -a
          java -version

