name: Build Tomcat

on: 
  push:
    branches:
      - passing-arguments-to-actions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out tomcat-users.xml
      uses: actions/checkout@v2

    - name: List project files and java version
      run: |
          ls -a
          java -version

    - name: Check out Apache Tomcat
      uses: actions/checkout@v2
      with:
        repository: apache/tomcat # Repository name with owner
        ref: master               # The branch, tag or SHA to checkout
        path: ./tomcat            # Relative path under $GITHUB_WORKSPACE

    - name: List project files and java version
      run: |
          ls -a
          java -version