name: Run Actions Workflow

on: [push]

jobs:
  Run-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Java Script Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Javed

      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"

      - name: List files before checkout
        run: |
          pwd
          ls -a
          # env variables are set automatically when a workflow is run.
          echo $GITHUB_SHA  ## commit id
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "{{github.token}}"  ##github object


      - name: checkout
        uses: actions/checkout@v1
         # git checkout action will clone the repo in our working directory in the virtual env. Using git checkout action is essentially same as we manually cloning the repo using the below two git commands
         # git clone git@github:$GITHUB_REPOSITORY
         # git checkout $GITHUB_SHA

      - name: List files after checkout
        run: |
          pwd
          ls -a
