name: workflow for wallmart us (wmtu)
on:
  push:
    branches:
      - wmtu

jobs:
  wmtu-job:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}

    - uses: actions/checkout@v2
    - name: S3 Sync
      uses: jakejarvis/s3-sync-action@v0.5.1

