name: workflow for wallmart us (wmtu)

on:
  push:
    branches:
      - wmtu

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: List S3 Buckets
      run: aws s3api list-buckets

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Copy files to the s3 website content bucket
      run:
        aws s3 cp locations.sql s3://${{ secrets.AWS_S3_BUCKET_NAME }}/wmtu/
