name: workflow for wallmart us (wmtu)

on:
  push:
    branches:
      - wmtu
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out sahmed448/wmtu
    - uses: actions/checkout@v1
    - name: Release to S3 bucket cp-dev-personal/wmtu
      run: bash scripts/pipeline/release.sh "cp-dev-personal" "folder1/myapp.zip" ${{secrets.AWS_Access_Key}} ${{secrets.AWS_Access_Secret}} "myapp.zip"